import { AutocompleteResult } from "../models/autocomplete-result";
import { CurrentWeatherResult } from "../models/current-weather-result";


export const LOCATIONS_AUTOCOMPLETE: AutocompleteResult[] = [
  {
    Version: 1,
    Key: "25257",
    Type: "City",
    Rank: 21,
    LocalizedName: "Adelaide",
    EnglishName: "Adelaide",
  },
  {
    Version: 1,
    Key: "16573",
    Type: "City",
    Rank: 55,
    LocalizedName: "Albany",
    EnglishName: "Albany",

  },
  {
    Version: 1,
    Key: "12402",
    Type: "City",
    Rank: 55,
    LocalizedName: "Bankstown",
    EnglishName: "Bankstown",
  },
  {
    Version: 1,
    Key: "13415",
    Type: "City",
    Rank: 55,
    LocalizedName: "Baulkham Hills",
    EnglishName: "Baulkham Hills",
  },
  {
    Version: 1,
    Key: "12090",
    Type: "City",
    Rank: 45,
    LocalizedName: "Belconnen",
    EnglishName: "Belconnen",
  },
  {
    Version: 1,
    Key: "15619",
    Type: "City",
    Rank: 55,
    LocalizedName: "Bentleigh East",
    EnglishName: "Bentleigh East",
  },
  {
    Version: 1,
    Key: "21000",
    Type: "City",
    Rank: 55,
    LocalizedName: "Berwick",
    EnglishName: "Berwick",
  },
  {
    Version: 1,
    Key: "22770",
    Type: "City",
    Rank: 55,
    LocalizedName: "Blacktown",
    EnglishName: "Blacktown",
  },
  {
    Version: 1,
    Key: "24741",
    Type: "City",
    Rank: 21,
    LocalizedName: "Brisbane",
    EnglishName: "Brisbane",

  },
  {
    Version: 1,
    Key: "16605",
    Type: "City",
    Rank: 45,
    LocalizedName: "Bunbury",
    EnglishName: "Bunbury",
  },
  {
    Version: 1,
    Key: "13968",
    Type: "City",
    Rank: 45,
    LocalizedName: "Cairns",
    EnglishName: "Cairns",
  },
  {
    Version: 1,
    Key: "1073964",
    Type: "City",
    Rank: 61,
    LocalizedName: "Campbelltown",
    EnglishName: "Campbelltown",
  },
  {
    Version: 1,
    Key: "21921",
    Type: "City",
    Rank: 30,
    LocalizedName: "Canberra",
    EnglishName: "Canberra",
  },
  {
    Version: 1,
    Key: "16537",
    Type: "City",
    Rank: 55,
    LocalizedName: "Canning Vale",
    EnglishName: "Canning Vale",
  },
  {
    Version: 1,
    Key: "13577",
    Type: "City",
    Rank: 55,
    LocalizedName: "Castle Hill",
    EnglishName: "Castle Hill",
  },
  {
    Version: 1,
    Key: "22793",
    Type: "City",
    Rank: 35,
    LocalizedName: "Central Coast",
    EnglishName: "Central Coast",
  },
  {
    Version: 1,
    Key: "15958",
    Type: "City",
    Rank: 55,
    LocalizedName: "Dandenong",
    EnglishName: "Dandenong",
  },
  {
    Version: 1,
    Key: "13718",
    Type: "City",
    Rank: 41,
    LocalizedName: "Darwin",
    EnglishName: "Darwin",
  },
  {
    Version: 1,
    Key: "16424",
    Type: "City",
    Rank: 63,
    LocalizedName: "Doreen",
    EnglishName: "Doreen",
  },
  {
    Version: 1,
    Key: "12764",
    Type: "City",
    Rank: 55,
    LocalizedName: "Dubbo",
    EnglishName: "Dubbo",
  },
  {
    Version: 1,
    Key: "20122",
    Type: "City",
    Rank: 55,
    LocalizedName: "Epping",
    EnglishName: "Epping",
  },
  {
    Version: 1,
    Key: "3497544",
    Type: "City",
    Rank: 55,
    LocalizedName: "Ferntree Gully",
    EnglishName: "Ferntree Gully",
  },
  {
    Version: 1,
    Key: "15976",
    Type: "City",
    Rank: 55,
    LocalizedName: "Frankston",
    EnglishName: "Frankston",
  },
  {
    Version: 1,
    Key: "15892",
    Type: "City",
    Rank: 45,
    LocalizedName: "Geelong",
    EnglishName: "Geelong",
  },
  {
    Version: 1,
    Key: "16643",
    Type: "City",
    Rank: 55,
    LocalizedName: "Geraldton",
    EnglishName: "Geraldton",

  },
  {
    Version: 1,
    Key: "20171",
    Type: "City",
    Rank: 55,
    LocalizedName: "Glen Waverley",
    EnglishName: "Glen Waverley",
  },
  {
    Version: 1,
    Key: "13978",
    Type: "City",
    Rank: 35,
    LocalizedName: "Gold Coast",
    EnglishName: "Gold Coast",
  },
  {
    Version: 1,
    Key: "12159",
    Type: "City",
    Rank: 55,
    LocalizedName: "Gungahlin",
    EnglishName: "Gungahlin",
  },
  {
    Version: 1,
    Key: "14224",
    Type: "City",
    Rank: 55,
    LocalizedName: "Hervey Bay",
    EnglishName: "Hervey Bay",

  },
  {
    Version: 1,
    Key: "3497533",
    Type: "City",
    Rank: 55,
    LocalizedName: "Hoppers Crossing",
    EnglishName: "Hoppers Crossing",
  },
  {
    Version: 1,
    Key: "12413",
    Type: "City",
    Rank: 55,
    LocalizedName: "Hurstville",
    EnglishName: "Hurstville",
  },
  {
    Version: 1,
    Key: "13972",
    Type: "City",
    Rank: 45,
    LocalizedName: "Ipswich",
    EnglishName: "Ipswich",
  },
  {
    Version: 1,
    Key: "15404",
    Type: "City",
    Rank: 45,
    LocalizedName: "Launceston",
    EnglishName: "Launceston",

  },
  {
    Version: 1,
    Key: "13090",
    Type: "City",
    Rank: 55,
    LocalizedName: "Lismore",
    EnglishName: "Lismore",
  },
  {
    Version: 1,
    Key: "26216",
    Type: "City",
    Rank: 11,
    LocalizedName: "Melbourne",
    EnglishName: "Melbourne",
  },
  {
    Version: 1,
    Key: "17256",
    Type: "City",
    Rank: 55,
    LocalizedName: "Merrylands",
    EnglishName: "Merrylands",
  },
  {
    Version: 1,
    Key: "26217",
    Type: "City",
    Rank: 55,
    LocalizedName: "Mildura",
    EnglishName: "Mildura",
  },
  {
    Version: 1,
    Key: "12416",
    Type: "City",
    Rank: 55,
    LocalizedName: "Mosman",
    EnglishName: "Mosman",
  },
  {
    Version: 1,
    Key: "20487",
    Type: "City",
    Rank: 55,
    LocalizedName: "Mount Waverley",
    EnglishName: "Mount Waverley",
  },
  {
    Version: 1,
    Key: "20524",
    Type: "City",
    Rank: 55,
    LocalizedName: "Narre Warren",
    EnglishName: "Narre Warren",
  },
  {
    Version: 1,
    Key: "3494107",
    Type: "City",
    Rank: 55,
    LocalizedName: "Narre Warren South",
    EnglishName: "Narre Warren South",
  },
  {
    Version: 1,
    Key: "12777",
    Type: "City",
    Rank: 35,
    LocalizedName: "Newcastle",
    EnglishName: "Newcastle",
  },
  {
    Version: 1,
    Key: "12470",
    Type: "City",
    Rank: 65,
    LocalizedName: "North Ryde",
    EnglishName: "North Ryde",
  },
  {
    Version: 1,
    Key: "12772",
    Type: "City",
    Rank: 55,
    LocalizedName: "Orange",
    EnglishName: "Orange",
  },
  {
    Version: 1,
    Key: "15895",
    Type: "City",
    Rank: 55,
    LocalizedName: "Pakenham",
    EnglishName: "Pakenham",
  },
  {
    Version: 1,
    Key: "13183",
    Type: "City",
    Rank: 65,
    LocalizedName: "Penrith",
    EnglishName: "Penrith",
  },
  {
    Version: 1,
    Key: "17394",
    Type: "City",
    Rank: 65,
    LocalizedName: "Penshurst",
    EnglishName: "Penshurst",
  },
  {
    Version: 1,
    Key: "26797",
    Type: "City",
    Rank: 21,
    LocalizedName: "Perth",
    EnglishName: "Perth",
  },
  {
    Version: 1,
    Key: "13192",
    Type: "City",
    Rank: 55,
    LocalizedName: "Port Macquarie",
    EnglishName: "Port Macquarie",

  },
  {
    Version: 1,
    Key: "15544",
    Type: "City",
    Rank: 55,
    LocalizedName: "Preston",
    EnglishName: "Preston",
  },
  {
    Version: 1,
    Key: "3496620",
    Type: "City",
    Rank: 65,
    LocalizedName: "Prestons",
    EnglishName: "Prestons",
  },
  {
    Version: 1,
    Key: "12541",
    Type: "City",
    Rank: 65,
    LocalizedName: "Punchbowl",
    EnglishName: "Punchbowl",
  },
  {
    Version: 1,
    Key: "22454",
    Type: "City",
    Rank: 65,
    LocalizedName: "Pymble",
    EnglishName: "Pymble",
  },
  {
    Version: 1,
    Key: "12484",
    Type: "City",
    Rank: 65,
    LocalizedName: "Pyrmont",
    EnglishName: "Pyrmont",
  },
  {
    Version: 1,
    Key: "17415",
    Type: "City",
    Rank: 55,
    LocalizedName: "Quakers Hill",
    EnglishName: "Quakers Hill",
  },
  {
    Version: 1,
    Key: "13196",
    Type: "City",
    Rank: 55,
    LocalizedName: "Queanbeyan",
    EnglishName: "Queanbeyan",
  },
  {
    Version: 1,
    Key: "13200",
    Type: "City",
    Rank: 65,
    LocalizedName: "Raymond Terrace",
    EnglishName: "Raymond Terrace",

  },
  {
    Version: 1,
    Key: "12458",
    Type: "City",
    Rank: 65,
    LocalizedName: "Redfern",
    EnglishName: "Redfern",
  },
  {
    Version: 1,
    Key: "20630",
    Type: "City",
    Rank: 55,
    LocalizedName: "Reservoir",
    EnglishName: "Reservoir",
  },
  {
    Version: 1,
    Key: "17431",
    Type: "City",
    Rank: 65,
    LocalizedName: "Revesby",
    EnglishName: "Revesby",
  },
  {
    Version: 1,
    Key: "12397",
    Type: "City",
    Rank: 65,
    LocalizedName: "Riverwood",
    EnglishName: "Riverwood",
  },
  {
    Version: 1,
    Key: "12414",
    Type: "City",
    Rank: 65,
    LocalizedName: "Rockdale",
    EnglishName: "Rockdale",
  },
  {
    Version: 1,
    Key: "13975",
    Type: "City",
    Rank: 55,
    LocalizedName: "Rockhampton",
    EnglishName: "Rockhampton",
  },
  {
    Version: 1,
    Key: "12542",
    Type: "City",
    Rank: 65,
    LocalizedName: "Roselands",
    EnglishName: "Roselands",
  },
  {
    Version: 1,
    Key: "20654",
    Type: "City",
    Rank: 55,
    LocalizedName: "Rowville",
    EnglishName: "Rowville",
  },
  {
    Version: 1,
    Key: "17459",
    Type: "City",
    Rank: 65,
    LocalizedName: "Rutherford",
    EnglishName: "Rutherford",

  },
  {
    Version: 1,
    Key: "12405",
    Type: "City",
    Rank: 65,
    LocalizedName: "Ryde",
    EnglishName: "Ryde",
  },
  {
    Version: 1,
    Key: "17475",
    Type: "City",
    Rank: 65,
    LocalizedName: "Seven Hills",
    EnglishName: "Seven Hills",
  },
  {
    Version: 1,
    Key: "2267549",
    Type: "City",
    Rank: 55,
    LocalizedName: "Shepparton",
    EnglishName: "Shepparton",

  },
  {
    Version: 1,
    Key: "14406",
    Type: "City",
    Rank: 55,
    LocalizedName: "Southport",
    EnglishName: "Southport",
  },
  {
    Version: 1,
    Key: "20699",
    Type: "City",
    Rank: 55,
    LocalizedName: "St Albans",
    EnglishName: "St Albans",
  },
  {
    Version: 1,
    Key: "16077",
    Type: "City",
    Rank: 55,
    LocalizedName: "Sunbury",
    EnglishName: "Sunbury",

  },
  {
    Version: 1,
    Key: "22889",
    Type: "City",
    Rank: 11,
    LocalizedName: "Sydney",
    EnglishName: "Sydney",
  },
  {
    Version: 1,
    Key: "15890",
    Type: "City",
    Rank: 55,
    LocalizedName: "Warrnambool",
    EnglishName: "Warrnambool",
  },
  {
    Version: 1,
    Key: "12104",
    Type: "City",
    Rank: 55,
    LocalizedName: "Woden Valley",
    EnglishName: "Woden Valley",
  }
]

export const CURRENT_WEATHER: CurrentWeatherResult[] = []
export const FUTURE_WEATHER: CurrentWeatherResult[] = []
